FROM python:3.9-slim

WORKDIR /app

# Install the airflow-exporter package
RUN pip install airflow-exporter

# Expose the default port used by the exporter
EXPOSE 9112

# Run it directly via Python module
CMD ["python", "-m", "airflow_exporter"]