scrape_configs:
  - job_name: 'airflow-webserver'
    metrics_path: /admin/metrics
    static_configs:
      - targets: ['airflow-webserver:8080']
    basic_auth:
      username: admin
      password: admin